//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace org.huesken.fauxmonet.net.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("org.huesken.fauxmonet.net.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///	&quot;name&quot;:&quot;hue emulator&quot;,
        ///	&quot;swversion&quot;:&quot;81012917&quot;,
        ///	&quot;bridgeid&quot;:&quot;##HUEID##&quot;,
        ///	&quot;portalservices&quot;:false,
        ///	&quot;linkbutton&quot;:false,
        ///	&quot;mac&quot;:&quot;##MAC##&quot;,
        ///	&quot;dhcp&quot;:true,
        ///	&quot;ipaddress&quot;:&quot;##IP##&quot;,
        ///	&quot;netmask&quot;:&quot;255.255.255.0&quot;,
        ///	&quot;gateway&quot;:&quot;192.168.1.1&quot;,
        ///	&quot;apiversion&quot;:&quot;1.3.0&quot;,
        ///	&quot;localtime&quot;:&quot;2017-12-03T12:07:32&quot;,
        ///	&quot;timezone&quot;:&quot;Europe/London&quot;,
        ///	&quot;whitelist&quot;:{&quot;api&quot;:{&quot;name&quot;:&quot;clientname#devicename&quot;}},
        ///	&quot;swupdate&quot;:{&quot;text&quot;:&quot;&quot;,&quot;notify&quot;:false,&quot;updatestate&quot;:0,&quot;url&quot;:&quot;&quot;}
        ///  } ähnelt.
        /// </summary>
        public static string config {
            get {
                return ResourceManager.GetString("config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;root xmlns=&quot;urn:schemas-upnp-org:device-1-0&quot;&gt;
        ///	&lt;specVersion&gt;
        ///		&lt;major&gt;1&lt;/major&gt;
        ///		&lt;minor&gt;0&lt;/minor&gt;
        ///	&lt;/specVersion&gt;
        ///	&lt;URLBase&gt;http://##URLBASE##&lt;/URLBase&gt;
        ///	&lt;device&gt;
        ///		&lt;deviceType&gt;urn:schemas-upnp-org:device:Basic:1&lt;/deviceType&gt;
        ///		&lt;friendlyName&gt;Philips hue (##URLBASE##)&lt;/friendlyName&gt;
        ///		&lt;manufacturer&gt;Royal Philips Electronics&lt;/manufacturer&gt;
        ///		&lt;manufacturerURL&gt;http://www.philips.com&lt;/manufacturerURL&gt;
        ///		&lt;modelDescription&gt;Philips hue Personal Wireless Lighting [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {&quot;manufacturername&quot;:&quot;OpenSource&quot;,&quot;modelid&quot;:&quot;LST001&quot;,&quot;name&quot;:&quot;Test 1&quot;,&quot;state&quot;:{&quot;on&quot;:false,&quot;hue&quot;:0,&quot;bri&quot;:0,&quot;sat&quot;:0,&quot;xy&quot;:[0.00000,0.00000],&quot;ct&quot;:500,&quot;alert&quot;:&quot;none&quot;,&quot;effect&quot;:&quot;none&quot;,&quot;colormode&quot;:&quot;hs&quot;,&quot;reachable&quot;:true},&quot;swversion&quot;:&quot;0.1&quot;,&quot;type&quot;:&quot;Dimmable light&quot;,&quot;uniqueid&quot;:&quot;60:01:94:0E:9E:F7-1&quot;}
        /// ähnelt.
        /// </summary>
        public static string light1 {
            get {
                return ResourceManager.GetString("light1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {&quot;manufacturername&quot;:&quot;OpenSource&quot;,&quot;modelid&quot;:&quot;LST001&quot;,&quot;name&quot;:&quot;Test 2&quot;,&quot;state&quot;:{&quot;on&quot;:false,&quot;hue&quot;:0,&quot;bri&quot;:0,&quot;sat&quot;:0,&quot;xy&quot;:[0.00000,0.00000],&quot;ct&quot;:500,&quot;alert&quot;:&quot;none&quot;,&quot;effect&quot;:&quot;none&quot;,&quot;colormode&quot;:&quot;hs&quot;,&quot;reachable&quot;:true},&quot;swversion&quot;:&quot;0.1&quot;,&quot;type&quot;:&quot;Dimmable light&quot;,&quot;uniqueid&quot;:&quot;60:01:94:0E:9E:F7-2&quot;}
        /// ähnelt.
        /// </summary>
        public static string light2 {
            get {
                return ResourceManager.GetString("light2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {&quot;1&quot;:{&quot;type&quot;:&quot;Dimmable light&quot;,&quot;manufacturername&quot;:&quot;OpenSource&quot;,&quot;swversion&quot;:&quot;0.1&quot;,&quot;name&quot;:&quot;Test 1&quot;,&quot;uniqueid&quot;:&quot;60:01:94:0E:9E:F7-1&quot;,&quot;modelid&quot;:&quot;LST001&quot;,&quot;state&quot;:{&quot;on&quot;:false,&quot;bri&quot;:0,&quot;alert&quot;:&quot;none&quot;,&quot;reachable&quot;:true}},&quot;2&quot;:{&quot;type&quot;:&quot;Dimmable light&quot;,&quot;manufacturername&quot;:&quot;OpenSource&quot;,&quot;swversion&quot;:&quot;0.1&quot;,&quot;name&quot;:&quot;Test 2&quot;,&quot;uniqueid&quot;:&quot;60:01:94:0E:9E:F7-2&quot;,&quot;modelid&quot;:&quot;LST001&quot;,&quot;state&quot;:{&quot;on&quot;:false,&quot;bri&quot;:0,&quot;alert&quot;:&quot;none&quot;,&quot;reachable&quot;:true}}}
        /// ähnelt.
        /// </summary>
        public static string lights {
            get {
                return ResourceManager.GetString("lights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [{&quot;success&quot;:{&quot;username&quot;:&quot;api&quot;}}]
        /// ähnelt.
        /// </summary>
        public static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///	&quot;1&quot;:{
        ///		&quot;type&quot;:&quot;Dimmable light&quot;,
        ///		&quot;manufacturername&quot;:&quot;OpenSource&quot;,
        ///		&quot;swversion&quot;:&quot;0.1&quot;,
        ///		&quot;name&quot;:&quot;Test 1&quot;,
        ///		&quot;uniqueid&quot;:&quot;60:01:94:0E:9E:F7-1&quot;,
        ///		&quot;modelid&quot;:&quot;LST001&quot;,
        ///		&quot;state&quot;:{
        ///			&quot;on&quot;:false,
        ///			&quot;bri&quot;:0,
        ///			&quot;alert&quot;:&quot;none&quot;,
        ///			&quot;reachable&quot;:true
        ///		}
        ///	},
        ///	&quot;2&quot;:{
        ///		&quot;type&quot;:&quot;Dimmable light&quot;,
        ///		&quot;manufacturername&quot;:&quot;OpenSource&quot;,
        ///		&quot;swversion&quot;:&quot;0.1&quot;,
        ///		&quot;name&quot;:&quot;Test 2&quot;,
        ///		&quot;uniqueid&quot;:&quot;60:01:94:0E:9E:F7-2&quot;,
        ///		&quot;modelid&quot;:&quot;LST001&quot;,
        ///		&quot;state&quot;:{
        ///			&quot;on&quot;:false,
        ///			&quot;bri&quot;:0,
        ///			&quot;alert&quot;:&quot;none&quot;,
        ///			&quot;re [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string wholeconfig {
            get {
                return ResourceManager.GetString("wholeconfig", resourceCulture);
            }
        }
    }
}
